name: test
channels:
  - robostack
  - conda-forge
dependencies:
  - python 3.8
  - compilers
  - ninja
  - cmake
  - catkin_pkg
  - pkg-config
  - rosdep
  - rosdistro
  - ros-distro-mutex 0.1 noetic
  - ros-noetic-catkin
  - ros-noetic-ros-environment
  - openssl 1.1.1*
  # we need the static library of this build
  - tinyxml2 9.0.0 *_1
