#### Python package 'rviz' initialization.
#
# The actual implementations are defined in C++ and wrapped by
# shiboken.  This is just a wrapper to make the namespaces work out
# nicely.

import sys

# Import the shared library generated by the shiboken binding-generator.
# This depends on the manifest.xml listing ${prefix}/lib in the python path.
import librviz_shiboken

# Expose the contained rviz namespace directly
sys.modules['rviz'] = librviz_shiboken.rviz
